---
title: "Course Notes"
author: "Eric Archer"
date: "September 30, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Spring 2017: April 3 - June 9 : 10 weeks


## -- Week 1 --

## R Console

commands and assignments executed or evaluated immediately
separated by new line (Enter/Return) or semicolon
recall commands with ↑ or ↓
case sensitive
*** EVERY command is executing a function ***


## Help

> help(mean)
> ?median
> help(“[“) 
> example(mean)
> help.search(“regression”)
www.r-project.org
www.r-bloggers.com

## RStudio




## Workspace

ls()
rm()
rm(list = ls())
save.image()
load(".rdata")
history()
#

## Assignment and data creation

<-
c()
seq()
:
rep
letters/LETTERS


## Data structures

Modes (atomic structures)
integer
numeric
character
logical

Classes
vector
factor
array
matrix
list
data.frame

Special Values
NULL
NA
NaN
Inf / -Inf

Object Information
str
mode
class
is.<class>
attr()
attributes


## Indexing



## Vectors

> x <- 1:10
> x
 [1]  1  2  3  4  5  6  7  8  9 10

> y <- c("a", "b", "d")

> str(x)
 int [1:10] 1 2 3 4 5 6 7 8 9 10

> is.numeric(x)
[1] TRUE
> class(y)
[1] "character"
> mode(x)
[1] "numeric"


Numeric Indexing
> x <- 21:30

> x[5]
[1] 25

> x[1:3]
[1] 21 22 23

> x[c(1, 5, 6)]
[1] 21 25 26

> x[c(8, 9, 3)]
[1] 28 29 23

> x[c(4, 6, 5, 6, 4)]
[1] 24 26 25 26 24

> x[c(1:4, 5, 10:8)]
[1] 21 22 23 24 25 30 29 28

> x[-3]
[1] 21 22 24 25 26 27 28 29 30


Character Indexing
> names(x) <- letters[1:10]
> x
 a  b  c  d  e  f  g  h  i  j 
21 22 23 24 25 26 27 28 29 30 

> str(x)
 Named int [1:10] 21 22 23 24 25 26 27 28 29 30
 - attr(*, "names")= chr [1:10] "a" "b" "c" "d" ...

> x["d"]
 d 
24 
> x[c("f", "a")]
 f  a 
26 21 

> names(x)[4] <- "fourth"
> x["fourth"]
fourth 
    24 


Logical indexing

> y <- 1:4

> y[c(T, T, F, T)]
[1] 1 2 4

> x <- 50:20
> x[x < 30]
 [1] 29 28 27 26 25 24 23 22 21 20

> x[x < 40 & x > 25]
 [1] 39 38 37 36 35 34 33 32 31 30 29 28 27 26

> x[x < 25 | x > 43]
 [1] 50 49 48 47 46 45 44 24 23 22 21 20

> x[-1:6]
Error in x[-1:6] : only 0's may be mixed with negative subscripts


Logical Operators


Vectorization



## -- Week 2 --

## Factors

> x <- factor(c("yellow", "blue", "green", "blue", "Blue", "yellow"))

> x
[1] yellow blue   green  blue   Blue   yellow
Levels: Blue blue green yellow

> str(x)
 Factor w/ 4 levels "Blue","blue",..: 4 2 3 2 1 4

> is.numeric(x)
[1] FALSE
> is.character(x)
[1] FALSE

> class(x)
[1] "factor"
> mode(x)
[1] "numeric”

> as.numeric(x)
[1] 4 1 3 1 2 4
> as.character(x)
[1] "yellow" "blue"   "green"  "blue"   "Blue"   "yellow"


## Matrices / arrays



## -- Week 3 -- 

## Lists

## Data Frames

## Reading and writing



## -- Week 4 --

## Data summary

## Data selection and manipulation



## -- Week 5 --

## Functions and flow control



## -- Week 6 --

## 'apply' family



## -- Week 7 --

## Graphics: base and ggplot2



## -- Week 8 --

## Statistics and model fitting



## -- Week 9 --

## Date and time handling

## Special functions (do.call, etc.)



## -- Week 10 --

## Example