---
title: "SIOB 296 - Introduction to Programming with R"
author: "Eric Archer"
output: pdf_document
---

SIOB 296:  "Introduction to Programming with R"     
Section: 902537  
Dates: April 4, 2017 - June 6, 2017  
Time: Tuesday 2:00 - 5:00pm  
Location: Eckart Building, first floor, Sea Cave  
Four Units, S/U Grading Only  

Contact: 
  Eric Archer   
  eric.archer@noaa.gov  
  858-546-7121  

## Course Description

This course will focus on establishing a solid fundamental understanding of data manipulation and analysis with R. No programming experience is necessary, and all backgrounds are welcome. We will start with an introduction to the R command line, followed by a detailed description of R data structures and how to manipulate them. The course will continue by covering commonly used R functions and students will then learn how to write their own functions and scripts. We will end by exploring visualization in R using base R graphics and the ggplot2 package. For the final project, students will write an R script to analyse their own data as well as edit R scripts from other students.

## Software

Students should come with the latest versions of R and RStudio loaded on their laptops. They can be obtained at:

R: https://www.r-project.org  
RStudio: https://www.rstudio.com

## Syllabus

Week 1 (4/4)    R console, RStudio, data structures, vectors, indexing, logical operations  
Week 2 (4/11)   factors, matrices and arrays, indexing review  
Week 3 (4/18)   lists, data frames, reading and writing data  
Week 4 (4/25)   common functions for data summary and selection  
Week 5 (5/2)    character and string manipulation  
Week 6 (5/9)    function writing and flow control  
Week 7 (5/16)   `apply` family of functions  
Week 8 (5/23)   graphics: `base` and `ggplot2`  
Week 9 (5/30)   statistics and model fitting  
Week 10 (6/6)   date and time handling, `tidyr` and `dplyr`, other special functions  

## Text

Davies, T. 2016. The Book of R: A First Course in Programming and Statistics. No Starch Press. 832pp ISBN 978-1593276515

## Other Resources

* Matloff, N. 2011. The Art of R Programming: A Tour of Statistical Software Design. No Starch Press. 400pp ISBN 978-1593273842
* R Bloggers: https://www.r-bloggers.com
* Base R Cheat Sheet: https://www.rstudio.com/wp-content/uploads/2016/10/r-cheat-sheet-3.pdf
* R Reference Card: https://cran.r-project.org/doc/contrib/Short-refcard.pdf
* Other Documentation: http://cran.stat.ucla.edu/other-docs.html


